[package]
name = "agentic_stablecoin"
version = "0.1.0"
edition = "2021"

[lib]
name = "agentic_stablecoin"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-timers = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ic-stable-structures = "0.6"

[features]
default = []
